export const eventsData = [
    {
        id: 1,
        title: "Milenaya Mektuplar",
        description: "Kafka ve Milena, Prag’da tanışmışlardır. Milena gazetecidir ve iyi derecede Çek diline hakimdir. Kafka ile olan dostlukları, Kafka'nın yazılarını Çekçe’ye çevirmesini istemesiyle başlar. ",
        category: "Tiyatro",
        date: "5 Ocak",
        clock: "19.30",
        location: "Sivas Kültür Merkezi",
        price: 50,
        studentPrice: 30,
        capacity: 100,
        usedCapacity: 23,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/milenaya-mektuplar-20241118134628123cd6980a8c43a58934f8813c44d0a9.jpg",
    },
    {
        id: 2,
        title: "Benim Küçük Yıldızım",
        description:
            "Bir gün bir yıldız kayar… Gökyüzünden… Küçük kız onun peşine düşer… Belki gözündeki yıldıza ulaşamaz; ama bir yıldız şarkıcı kargaya, tavuklar için bir Yıldız gibi pırıl pırıl parlayan bir mısır tanesine, her nefes aldıkça bir yıldız parıldayan ateş böceğine rastlar… Hepsiyle arkadaş olur… Sonunda gerçek yıldızın içinde olduğunu sevgi kardeşlik dostluk olduğunu anlar.",
        category: "Tiyatro",
        date: "25 Aralık",
        clock: "10.00",
        location: "Sivas DT",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 92,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/benim-kucuk-yildizim-20241261381908a3c4c46c4d4cb7a019e98f5529fdd7.jpg",
    },
    {
        id: 3,
        title: "Çılgın Mucitler",
        description:
            "Bilim ve tiyatro ilk kez sahnede buluşuyor. Çocukların en sevdiği kahramanlardan oluşan bu gösteri size zamanda yolculuk yaptırmaya hazırlanıyor. Birbirinden heyecanlı maceraların en unutulmazına hazır olun. Bilim hiç bu kadar eğlenceli olmamıştı.",
        category: "Tiyatro",
        date: "4 Ocak",
        clock: "15.00",
        location: "Sivas Muhsin Yazıcıoğlu Kültür Merkezi",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 56,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/cilgin-mucitler-202411111440569b53c655b60548fc93067142b18ef027.jpg",
    },
    {
        id: 4,
        title: "GİZLİ BAHÇE'NİN BEZELYESİ",
        description:
            "Filozof Çocuklar İçin Hikâyeler Projesi’nin ikinci oyunu olarak kaleme alınan Gizli Bahçe’nin Bezelyesi, 3-6 yaş çocuklara özel interaktif anlatım biçimiyle, ormanın ünlü aşçısı Bay Bezelye’nin sevdiği işi yaparken maceraları konu ediniyor.",
        category: "Tiyatro",
        date: "5 Ocak",
        clock: "14.00",
        location: "Sivas DT",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 10,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/benim-kucuk-yildizim-20241261381908a3c4c46c4d4cb7a019e98f5529fdd7.jpg",
    },
    {
        id: 5,
        title: "Kalabalık Duası",
        description: "Fiziksel Tiyatro Araştırmaları, Şatonun Altında'dan sonra yepyeni bir araştırmanın sonucunu seyirciyle paylaşmaya hazır. Bu defa özgün bir metni sahneye taşırken anlatının fiziksel ve disiplinler arası olanaklarının peşine düşüyoruz. ",
        category: "Tiyatro",
        date: "13 Ocak",
        clock: "20.00",
        location: "Sivas Muhsin Yazıcıoğlu Kültür Merkezi",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 60,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/kalabalik-duasi-2022215112248.jpg",
    },
    {
        id: 6,
        title: "Metin Kemal Kahraman 30. Yıl Konserleri",
        description: "“Metin & Kemal Kahraman kardeşler, ilk albümlerini yayınlayışlarının 30. yılını kutluyor! 30 yıl boyunca kültürümüzün zenginliğini ezgilerle anlatan, dillerden düşmeyen şarkılarla nice gönüllere dokunan bu özel yolculuğa hep birlikte tanıklık ettik. ",
        category: "Müzik",
        date: "16 Ocak",
        clock: "20.30",
        location: "Sivas Muhsin Yazıcıoğlu Kültür Merkezi",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 100,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/metin-kemal-kahraman-20241217174549501022ef13f4cada63c0c3b29a495f6.jpg",
    },
    {
        id: 7,
        title: "Uğur Böceği ile Kara Kedi",
        description: "Sevilen kahramanlar Uğur Böceği ve Kara Kedi, şimdi yepyeni bir macera ile sahnede! Marinette ve Adrien’in sihirli dönüşümleriyle hayat bulan bu iki cesur kahraman, izleyicilerini heyecan dolu bir serüvene davet ediyor.",
        category: "Tiyatro",
        date: "17 Ocak",
        clock: "15.00",
        location: "Sivas Muhsin Yazıcıoğlu Kültür Merkezi",
        price: 40,
        studentPrice: 25,
        capacity: 150,
        usedCapacity: 20,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/ugur-bocegi-kara-kedi-202412921113f1e800347ef4c1aa800663d58340b70.jpg",
    },
    {
        id: 8,
        title: "Sagopa Kajmer Konseri",
        description: "Sagopa Kajmer, uzun bir aradan sonra hayranlarının beğenisine sunduğu “Kağıt Kesikleri” albümü, arabesk müziğin güçlü sesi Mine Koşan’la yaptığı “Geceler” düeti ve son teklisi “İstesem de Söyleyemem” ile hayranlarından yine tam not aldı.  ",
        category: "Müzik",
        date: "26 Şubat",
        clock: "20.30",
        location: "Sivas Cumhuriyet",
        price: 600,
        studentPrice: null,
        capacity: 150,
        usedCapacity: 90,
        image: "https://cdn.bubilet.com.tr/files/Etkinlik/sagopa-kajmer-konseri-88627.jpg",
    },
    {
        id: 9,
        title: "Çakallarla Dans 7",
        description: "Serinin yedinci halkası, ekibin dünya çapında bir güzellik yarışmasının organizasyonunda görev almak için gittikleri İzmir’de yaşadıkları maceraları takip ediyor.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "11.15-21.00",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: null,
        capacity: 140,
        usedCapacity: 75,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/cakallarla-dans-7-20241125152717d75af11cb5aa4840acb7ed62ddeef517.jpg",
    },
    {
        id: 10,
        title: "Moana 2",
        description: "Atalarından kendisine rehberlik etmesi için beklenmedik bir çağrı alan Moana, Okyanusya'nın uçsuz bucaksız denizlerine ve tehlikeli, çoktan unutulmuş sulara giderek daha önce deneyimlediği hiçbir maceraya benzemeyen bir maceraya atılır.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "11.15-20.00",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: null,
        capacity: 140,
        usedCapacity: 50,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/moana-2-202411261148548043e736f8d74b0080ca48f2a7396a26.jpg",
    },
    {
        id: 11,
        title: "Mufasa: Aslan Kral",
        description: "Filmde Mufasa, efsanesini Simba ve Nala’nın kızı aslan yavrusu Kiara’ya aktarması için Rafiki’den yardım istiyor. Timon ve Pumbaa da kendilerine özgü şakalarını paylaşmaktan kaçınmıyor. ",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "11.15-21.00",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: null,
        capacity: 140,
        usedCapacity: 15,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/mufasa-aslan-kral-202412191710acf4a4ddbbc94c55924d05f1e25f9856.jpg",
    },
    {
        id: 12,
        title: "Nasreddin Hoca Zaman Yolcusu: Kadim Medeniyetler",
        description: "Film, antik medeniyetlerin gizemli dünyasına zaman yolculuğu yapan Nasreddin Hoca ve genç dostlarının maceralarını anlatıyor.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "11.15-16.30",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: null,
        capacity: 140,
        usedCapacity: 25,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/nasreddin-hoca-zaman-yolcusu-kadim-medeniyetler-2024124105410059a1cd7630c49909d2b942544f55a90.jpg",
    },
    {
        id: 13,
        title: "Gen 2",
        description: "Hikaye onsekiz yıl sonra devam ediyor. Vahşi, psikopat bir katilin elinden nasıl kurtulabilirsiniz? Korku türündeki Gen 2 filminin yönetmen koltuğunda Gökhan Murat Toktamışoğlu oturuyor.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "12.15-14.15",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: null,
        capacity: 140,
        usedCapacity: 25,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/gen-2-20241217105048e95766c4d812479098e5eedbfebd00da.jpg",
    },
    {
        id: 14,
        title: "Şımarık",
        description: "Film, zengin bir babanın, şımarık oğlu Mete'ye büyük bir ders vermek için onu zamanda yolculuk yaptığına ikna etmesi ve Mete'nin 16. yüzyıl Osmanlı İmparatorluğu'nda bir köyde olduğuna inanmasıyla gelişen olayları konu ediniyor.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "12.15-21.00",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: 140,
        capacity: 140,
        usedCapacity: 25,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/simarik-202412171173007f80b56c08246ca9adcac05c5a93efd.jpg",
    },
    {
        id: 15,
        title: "Avcı Kraven",
        description: "Film, babasının kendisini ölüme terk ettiği aslan saldırısından özel güçler kazanarak çıkan Sergei Kravinoff'un Avcı Kraven'a dönüşümünü konu ediniyor.",
        category: "Sinema",
        date: "23-24-25-26 Aralık",
        clock: "18.15-20.45",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: 140,
        capacity: 140,
        usedCapacity: 25,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/avci-kraven-2024121174842d43cff3a6836404faa053ff43e3c09ef.jpg",
    },
    {
        id: 16,
        title: "On Saniye",
        description: "Ülkenin en prestijli lisesi William College’ta sıradışı bir gün. Bir son sınıf öğrencisinin çektiği “kedi öldürme” videosu okuldan atılmasına neden olmuştur.",
        category: "Sinema",
        date: "25 Aralık",
        clock: "20.45",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: 140,
        capacity: 140,
        usedCapacity: 5,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/on-saniye-20241115163285718ebd92cf44055a6c13b530f212837.jpg",
    },
    {
        id: 17,
        title: "Rafadan Tayfa: Kapadokya",
        description: "Filmde Rafadan Tayfa, bağ bozumu festivalinde gerçekleşecek “Kapadokya Bilmece Avı” etkinliği için Nevşehir’e gitmiştir.",
        category: "Sinema",
        date: "27-28-29 Aralık",
        clock: "11.00-20.45",
        location: "Sivas İva Park Avşar",
        price: 145,
        studentPrice: 140,
        capacity: 140,
        usedCapacity: 80,
        image: "https://b6s54eznn8xq.merlincdn.net/Uploads/Films/rafadan-tayfa-kapadokya-20241217162118eef686a16e3c489ebe00e7ef14b8508c.png",
    },
];
