export const locationsData = [
    {
        id: 1,
        title: "Hookah90lar Kafe",
        description: "90lar konseptli bir kafe.",
        category: "Kafe",
        clock: "07.30-01.00",
        rating: 4.5,
        image: "https://lh3.googleusercontent.com/p/AF1QipOKn8p9qlElVCiobHuun8a68IeYRCgpACr07UKE=s1360-w1360-h1020-rw",
    },
    {
        id: 2,
        title: "Tarihi Behrampaşa Hanı",
        description: "Sivas yöresine ve dünya mutfağına ait en lezzetli yemekleri, tarihi bir mekanda yiyebilirsiniz",
        category: "Kafe",
        clock: "07.30-01.00",
        rating: 4.5,
        image: "https://imgkit.otelz.com/turkiye/sivas/sivas-merkez/behrampasa-otel-cafe-restaurant_3ef2577c.jpg?tr=w-500,h-360,fo-auto,q-70",
    },
    {
        id: 3,
        title: "Teras Kafe",
        description: "Sivas manzarası eşliğinde kahvaltınızı ve yemeklerinizi yiyebilirsiniz.",
        category: "Kafe",
        clock: "08.00-00.00",
        rating: 4.6,
        image: "https://lh3.googleusercontent.com/p/AF1QipMGAC08kwNarOLOgPU09QGeBkfhX7tJhIiKaRJj=s1360-w1360-h1020-rw",
    },
    {
        id: 4,
        title: "Libro Library Kafe",
        description: "Bağdat caddesinde bulunan bu kafede farklı tatlar deneyimleyebilirsiniz.",
        category: "Kafe",
        clock: "12.00-01.00",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/p/AF1QipO0PHwhoZaT53Qjx0Des7P79d2W9ih5OfgCj3xb=s1360-w1360-h1020-rw",
    },
    {
        id: 5,
        title: "Hygge Coffee House",
        description: "Lezzetli kahve ve tatlıların mekanı",
        category: "Kafe",
        clock: "10.00-23.00",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/p/AF1QipPDIK0LHexX7UORruGaXxVSdIDgU0Z_ec7rqNNl=s1360-w1360-h1020-rw",
    },
    {
        id: 6,
        title: "Lezzetçi",
        description: "Sivas yöresine ait yemekler yiyip, çorbalar içebilirsiniz",
        category: "Restorant",
        clock: "06.00-23.00",
        rating: 4.3,
        image: "https://lh3.googleusercontent.com/p/AF1QipPMfgW_6-wWGEjuZrpr051yqw2IswYXeWtMGXrJ=s1360-w1360-h1020-rw",
    }, 
    {
        id: 7,
        title: "Tarihi Buruciye Restoran",
        description: "Sivas yöresine ait yemekler yiyip, çorbalar içebilirsiniz",
        category: "Restorant",
        clock: "11.00-23.00",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/p/AF1QipM4GCZjZcHB2Z6gchPTAxvxklWhoJqq2Ddmw6om=s1360-w1360-h1020-rw",
    }, 
    {
        id: 8,
        title: "Aşçıbaşı",
        description: "Sivas yöresel yemeklerini yiyip, çorbalar içebilirsiniz",
        category: "Restorant",
        clock: "07.00-22.00",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/p/AF1QipM73sSLG_S5aEODCkjJfxLRD9pEe5_9d2U30A6s=s1360-w1360-h1020-rw",
    }, 
    {
        id: 9,
        title: "Mücahit Etli Pide",
        description: "Sivas etliekmeğinin tadına bakabilirsiniz",
        category: "Restorant",
        clock: "09.00-21.30",
        rating: 4.5,
        image: "https://lh3.googleusercontent.com/p/AF1QipNdddjY-jtwc2sTx-UqrujLuGsayur_dqfAO7_L=s1360-w1360-h1020-rw",
    }, 
    {
        id: 10,
        title: "Kanatçı Park",
        description: "Lezzetli kanatların ve tavuk ürünlerinin adresi",
        category: "Restorant",
        clock: "09.00-21.30",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/p/AF1QipOhad30OYUi0hYu9jEkcYyX8dogfxzIruv70mGW=s1360-w1360-h1020-rw",
    }, 
    {
        id: 11,
        title: "Baklavacı Orhan Anteplioğlu",
        description: "Lezzetli baklava ve tatlıların adresi",
        category: "Tatlı",
        clock: "08.00-00.00",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/p/AF1QipM32ZLWudM7gy5PRM1lXmu_mWoe2b2q4njTn1ah=s1360-w1360-h1020-rw",
    }, 
    {
        id: 12,
        title: "Tatlıcı Fehmi Usta",
        description: "Hikmet Işık caddesinde bulunan lezzetli tatlıların adresi",
        category: "Tatlı",
        clock: "10.30-23.00",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/p/AF1QipMykFleLE58B2cW7P68jvpHZzAMfG-B3thWZy0O=s1360-w1360-h1020-rw",
    }, 
    {
        id: 13,
        title: "Sultana Künefe Katmer",
        description: "Kardeşler mahallesinde lezzetli künefe ve katmerlerin adresi",
        category: "Tatlı",
        clock: "09.00-02.00",
        rating: 4.0,
        image: "https://lh3.googleusercontent.com/p/AF1QipP8eQAA2bM7wv19iE0w1YJ72n2NzmZLk6RGOpJk=s1360-w1360-h1020-rw",
    }, 
    {
        id: 14,
        title: "Yeşil Künefe",
        description: "Lezzetli künefe ve katmerlerin vazgeçilmez adresi",
        category: "Tatlı",
        clock: "11.00-00.00",
        rating: 4.0,
        image: "https://lh3.googleusercontent.com/p/AF1QipNhteQBq4cFLulZX8RYEK1J4dOROsGEgi5eZtbl=s1360-w1360-h1020-rw",
    }, 
    {
        id: 15,
        title: "Sivas Kelle Çorbacısı",
        description: "Lezzetli çorbalar ve kellenin adresi",
        category: "Çorba",
        clock: "04.30-20.00",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/p/AF1QipPFLSgvFPiRB2srYYLd9PqWdGbjtcrrsBstgKm6=s1360-w1360-h1020-rw",
    }, 
    {
        id: 16,
        title: "Lezzetçi Çorbacım",
        description: "Lezzetli çorbaların adresi",
        category: "Çorba",
        clock: "04.30-02.00",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/p/AF1QipNe072sLrAseQsQYrxadkq8Xh48QaxgqVr56jcJ=s1360-w1360-h1020-rw",
    }, 
    {
        id: 17,
        title: "Makam Çorba",
        description: "Lezzetli çorbaların ve köftelerin adresi",
        category: "Çorba",
        clock: "04.00-23.00",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/p/AF1QipPgQI5gvDr1UVXjRoulLbK-tLMGT91n3-GrwA-g=s1360-w1360-h1020-rw",
    }, 
    {
        id: 18,
        title: "Akin Kellecisi",
        description: "Lezzetli kelle ve çorbaların adresi",
        category: "Çorba",
        clock: "04.30-17.00",
        rating: 3.3,
        image: "https://lh3.googleusercontent.com/p/AF1QipOEjP4sAyiveJVuhPFSgxwLmnoTm0_EY5rGJRlE=s1360-w1360-h1020-rw",
    }, 
    {
        id: 19,
        title: "Pişi Kahvaltı",
        description: "Lezzetli pişi ve gözlemelerin adresi",
        category: "Kahvaltı",
        clock: "08.30-15.30",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/p/AF1QipPKyHP6y4ElFSEf9179eDoRMEWBs6xHrIIczsyc=s1360-w1360-h1020-rw",
    }, 
    {
        id: 20,
        title: "Tostçu Raşit Usta",
        description: "Lezzetli tostların adresi",
        category: "Kahvaltı",
        clock: "24 saat açık",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/p/AF1QipNi7lkjiM39aNxKodOmIRBYQqq6rB1J1zPL1vwj=s1360-w1360-h1020-rw",
    }, 
    {
        id: 21,
        title: "Brother's",
        description: "Acıklama bulunamadı",
        category: "Bar",
        clock: "14.00-00.00",
        rating: 4.1,
        image: "https://lh3.googleusercontent.com/p/AF1QipMSJjtYBVRxqlZIkFS5ZaWQI6YeyuVGwDyJUcjf=s1360-w1360-h1020-rw",
    }, 
    {
        id: 22,
        title: "Sis Pub",
        description: "Acıklama bulunamadı",
        category: "Bar",
        clock: "14.00-02.00",
        rating: 3.6,
        image: "https://lh3.googleusercontent.com/p/AF1QipNcSiHqlQoUrutT0UNc6p5rZMlwRJMNeHs4DN-r=s1360-w1360-h1020-rw",
    }, 
    {
        id: 23,
        title: "Gece Bar",
        description: "Acıklama bulunamadı",
        category: "Bar",
        clock: "15.00-00.00",
        rating: 2.3,
        image: "https://lh3.googleusercontent.com/p/AF1QipONPNPnv9qPXRdYNo8GYaL7AgczcHrO7p_kBMjs=s1360-w1360-h1020-rw",
    }, 
    {
        id: 24,
        title: "Şale Kitap Kafe",
        description: "Hamidiye millet bahçesinde tarih ve kitap eşliğinde kahve keyfi yapabilirsiniz",
        category: "Kitap Kafe",
        clock: "09.00-20.00",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/p/AF1QipN0bhs336rrjIg6aq5BeLKbYoP9X5fxj3NbTKij=s1360-w1360-h1020-rw",
    }, 
    {
        id: 25,
        title: "Pasaj Sahaf",
        description: "Merkezde kitap eşliğinde çay ve kahve keyfi yapabilirsiniz",
        category: "Kitap Kafe",
        clock: "11.00-21.00",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/p/AF1QipPB8G9kvuYXegJewsKyObzTONFAS_lLjBoDeDl3=s1360-w1360-h1020-rw",
    }, 
    {
        id: 26,
        title: "David People Coffee",
        description: "Lezzetli tatlı ve kahvelerin yeni adresi",
        category: "Kafe",
        clock: "09.00-00.00",
        rating: 3.8,
        image: "https://lh3.googleusercontent.com/p/AF1QipMWMhVLw9_96OPPEH9_MOBzui8GMBd6HLbPZG7b=s1360-w1360-h1020",
    }, 
    {
        id: 27,
        title: "Macviper",
        description: "Lezzetli kahvel ve diğer içecekleri tadabilirsiniz",
        category: "Kafe",
        clock: "08.30-01.00",
        rating: 4.3,
        image: "https://lh3.googleusercontent.com/p/AF1QipMMFGtgeJaYcy8vCXlLZUlUxyGgaT5bj6McYXSi=s1360-w1360-h1020",
    }, 
]