export const locationsData = [
    {
        id: 1,
        title: "Divriği Ulu Camii",
        description: "Selçuklu dönemine ait, UNESCO Dünya Mirası Listesi'nde yer alan tarihi cami.",
        category: "Camii",
        location: "Divriği, Sivas",
        image: "https://www.howturkey.com/images/sivas_divrigi_dunya_mirasi_unesco_2.jpg",
    },
    {
        id: 2,
        title: "Sivas Kalesi",
        description: "Sivas Kalesi, Roma dönemine kadar uzandığı bilinen ve şehri çevreleyen tarihi bir kaledir. Orta Çağ'dan kalma surları ve gözetleme kuleleriyle, şehir manzarası sunan önemli bir yapıdır.",
        category: "Kale",
        location: "Sivas",
        image: "https://www.bizimsivas.com.tr/images/haberler/2023/07/tmpbc764ie7.jpg",
    },
    {
        id: 3,
        title: "Gökmedrese",
        description: "Gökmedrese, 1271 yılında Selçuklu Sultanı III. Alaeddin Keykubad döneminde yapılmış ve Anadolu'nun en eski medreselerinden biridir. Mimarisindeki mavi çini süslemeler nedeniyle 'Gökmedrese' olarak anılmaktadır.",
        category: "Medrese",
        location: "Sivas",
        image: "https://www.sivasagel.com/wp-content/uploads/2019/02/D_iw6h7XUAIc2KR.jpg",
    },
    {
        id: 4,
        title: "Sivas Atatürk Kongre Müzesi",
        description: "Sivas Atatürk Kongre Müzesi, Türk Kurtuluş Savaşı'nın önemli dönüm noktalarından birini oluşturan Sivas Kongresi'ne ev sahipliği yapmıştır. Müze, bu dönemin belgeleri ve hatıralarını sergilemektedir.",
        category: "Müze",
        location: "Sivas",
        image: "https://visitsivas.com/assets/images/yerler/galeri/850_450_kongre_m%C3%BCzesi2.jpg",
    },
    {
        id: 5,
        title: "Sivas Arkeoloji Müzesi",
        description: "Sivas Arkeoloji Müzesi, bölgedeki arkeolojik kazılardan çıkarılan Roma ve Bizans dönemine ait eserlerin sergilendiği önemli bir kültürel merkezdir.",
        category: "Müze",
        location: "Sivas",
        image: "https://www.kulturportali.gov.tr/repoKulturPortali/large/21062013/805f52cf-1f73-4ede-9ab3-6820d3e26d40.JPG?format=jpg&quality=50",
    },
    {
        id: 6,
        title: "Abdulhamit Han Anı Evi",
        description: "Osmanlı padişahı II. Abdulhamit'in anısına yapılmış olan bu ev, Sivas'ın tarihi dokusuna katkı sağlamaktadır.",
        category: "Müze",
        location: "Sivas",
        image: "https://visitsivas.com/assets/images/muzeler/galeri/VLLK3651.JPG",
    },
    {
        id: 7,
        title: "Şifaiye Medresesi",
        description: "Selçuklu döneminden kalma Şifaiye Medresesi, tıp eğitimi verilen önemli bir eğitim kurumuydu.",
        category: "Medrese",
        location: "Sivas",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQKKMMWMFThzejP5pWypJKRli8uKQDkWLTIDUTrH-v2NkJh984t5BVCusvNdx2T27r2Ar9fyQZO7qjDXN-xfdE02DH99BA59iPFbT2Tvw",
    },
    {
        id: 8,
        title: "Sanayi Mektebi Müzesi",
        description: "Sanayi Mektebi, Osmanlı döneminden günümüze gelen endüstriyel eğitim yapılarından biridir. Şu anda bir müze olarak hizmet vermektedir.",
        category: "Müze",
        location: "Sivas",
        image: "https://www.arkeolojisanat.com/upload/data/images/1_1001.jpg",
    },
    {
        id: 9,
        title: "Savaş Atları Müzesi",
        description: "Türk tarihinde önemli bir yeri olan savaş atlarının sergilendiği bu müze, Türk kültürüne olan katkıları nedeniyle dikkat çeker.",
        category: "Müze",
        location: "Sivas",
        image: "https://visitsivas.com/assets/images/muzeler/galeri/127.JPG",
    },
    {
        id: 10,
        title: "Aşık Veysel Müzesi",
        description: "Türk halk müziğinin önemli isimlerinden Aşık Veysel'in hayatı ve eserlerinin sergilendiği bu müze, ona olan saygıyı yansıtan bir mekan.",
        category: "Müze",
        location: "Sivas",
        image: "https://turkiyeturizmansiklopedisi.com/uploads/img/2023/07/04/e8f970daa369992078d34da41f370aecab5f4eac.gif",
    },
    {
        id: 11,
        title: "Muhsin Yazıcıoğlu Anı Evi",
        description: "Sivas'ta hayatını kaybeden Muhsin Yazıcıoğlu'nun anısına inşa edilen bu müze, siyasi ve sosyal hayatına dair önemli belgeleri içeriyor.",
        category: "Müze",
        location: "Sivas",
        image: "https://www.sivasekspres.com/files/uploads/news/default/1725437108.webp",
    },
    {
        id: 12,
        title: "Sıcak Çermik",
        description: "Sivas'ta bulunan termal kaplıcalar, dinlendirici ve sağlık verici özelliklere sahiptir.",
        category: "Termal Kaplıca",
        location: "Sivas",
        image: "https://cdn.gezelim.com/2022/02/Altinkale_011.jpg",
    },
    {
        id: 13,
        title: "Kızılırmak Nehri",
        description: "Sivas'tan geçen Türkiye'nin en uzun nehridir, bölgedeki doğal güzellikler arasında önemli bir yer tutar.",
        category: "Doğal Güzellik",
        location: "Sivas",
        image: "https://cdnuploads.aa.com.tr/uploads/Contents/2022/06/10/thumbs_b_c_e240807a1329c4eaceb22887b8f10864.jpg?v=155040",
    },
    {
        id: 14,
        title: "Kangal Balıklı Kaplıca",
        description: "Dünyaca ünlü olan Kangal Balıklı Kaplıca, deri hastalıklarına iyi geldiği bilinen balıklarıyla ünlüdür. Sağlık açısından önemli bir turistik bölgedir.",
        category: "Termal Kaplıca",
        location: "Kangal, Sivas",
        image: "https://turkiyeturizmansiklopedisi.com/uploads/img/2023/07/05/95dc945b75b22cdcc43e6d4981dcbafa7e043511.jpg",
    },
    {
        id: 15,
        title: "Soğuk Çermik",
        description: "Balıkların deri hastalıklarına iyi geldiği bilinen Soğuk Çermik, sağlık açısından önemli bir termal kaplıcadır.",
        category: "Termal Kaplıca",
        location: "Kangal, Sivas",
        image: "https://visitsivas.com/assets/images/yerler/galeri/550x334_so%C4%9Fuk_%C3%A7ermik_(8).jpg",
    },
    {
        id: 16,
        title: "Gürün Gökpınar Gölü",
        description: "Sivas'ın doğal güzelliklerinden biri olan Gökpınar Gölü, çevresindeki zengin flora ve faunasıyla dikkat çeker.",
        category: "Doğal Güzellik",
        location: "Kangal, Sivas",
        image: "https://www.sivasagel.com/wp-content/uploads/2021/06/20210605_130202-scaled.jpg",
    },
    {
        id: 17,
        title: "Tödürge Gölü",
        description: "Tödürge Gölü, özellikle su sporları ve doğa yürüyüşleri için ideal bir alandır. Sivas'ın en bilinen doğal alanlarından biridir.",
        category: "Doğal Güzellik",
        location: "Kangal, Sivas",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Lake_T%C3%B6d%C3%BCrge_-_T%C3%B6d%C3%BCrge_G%C3%B6l%C3%BC%2C_Sivas_06.jpg/1200px-Lake_T%C3%B6d%C3%BCrge_-_T%C3%B6d%C3%BCrge_G%C3%B6l%C3%BC%2C_Sivas_06.jpg",
    },
    {
        id: 18,
        title: "Paşabahçe Mesire Alanı",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Park",
        location: "Kangal, Sivas",
        image: "https://www.sivasbiliyor.com/wp-content/uploads/2023/05/PASA-BAHCE2.jpg",
    },
    {
        id: 19,
        title: "Hafik Gölü",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Doğal Güzellik",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/7b/d7/44/hafik-golu.jpg?w=1000&h=800&s=1",
    },
    {
        id: 20,
        title: "Aksu Parkı",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Park",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/6e/e8/12/aksu-parki-1.jpg?w=1000&h=800&s=1",
    },
    {
        id: 21,
        title: "Yıldız Dağı",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Park",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/33/d8/4b/guzel-bir-gundu.jpg?w=1000&h=800&s=1",
    },
    {
        id: 22,
        title: "Millet Bahçesi",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Park",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/fa/16/8a/caption.jpg?w=1000&h=-1&s=1",
    },
    {
        id: 23,
        title: "27 Haziran Öğretmenler Parkı",
        description: "Dünyaca ünlü, balıkların deri hastalıklarına iyi geldiği bilinen termal kaplıca.",
        category: "Park",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/cf/20/a1/27-haziran-ogretmenler.jpg?w=1000&h=-1&s=1",
    },
    {
        id: 24,
        title: "Behrampaşa Hanı",
        description: " 1573 yılında Sağır Behram Paşa tarafından yaptırılmıştır. Kesme taş malzemeli, iki katlı ve ortası açık avlulu olarak inşa edilen hanın birde ahır kısmı mevcuttur. ",
        category: "Han",
        location: "Kangal, Sivas",
        image: "https://visitsivas.com/assets/images/yerler/galeri/850x450_behrampa%C5%9Fa_han%C4%B1_(6).jpg",
    },
    {
        id: 25,
        title: "Tarihi Taş Han Çarşısı",
        description: " 1573 yılında Sağır Behram Paşa tarafından yaptırılmıştır. Kesme taş malzemeli, iki katlı ve ortası açık avlulu olarak inşa edilen hanın birde ahır kısmı mevcuttur. ",
        category: "Han",
        location: "Kangal, Sivas",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/5c/79/a5/disardan-gorunus.jpg?w=1200&h=-1&s=1",
    },
    {
        id: 26,
        title: "Abdi Ağa Konağı",
        description: "“Mütevellizade Abdi Ağa” tarafından yaptırılmıştır. Mimari özelliklerine göre 19. yüzyıla tarihlendirilmektedir. Konak, Abdi Ağa’nın torunları tarafından kültür evi olarak kullanılmak üzere Sivas Belediyesi’ne bağışlanmıştır",
        category: "Konak",
        location: "Kangal, Sivas",
        image: "https://media-cdn.tripadvisor.com/media/photo-s/19/c6/88/06/abdi-aga-konagi.jpg",
    },
];
